Switch to external ca: fix certmonger script
The script renew_ca_cert produces a Traceback when switching
from self-signed to external CA:
Traceback (most recent call last):
  File "/usr/libexec/ipa/certmonger/renew_ca_cert", line 224, in <module>
    main()
  File "/usr/libexec/ipa/certmonger/renew_ca_cert", line 218, in main
    _main()
  File "/usr/libexec/ipa/certmonger/renew_ca_cert", line 184, in _main
     ca_flags = dict(cc[1:] for cc in ca_certs)[ca_nick]
KeyError: 'CN=Cert Auth,O=FloAuth.

It is trying to find a cert in a dict using a str as key,
while the keys are bytes.

Related: https://pagure.io/freeipa/issue/8879
Fixes: https://pagure.io/freeipa/issue/8893