CONFIGURE: Check for python module setuptools
It is required for installation of python modules therefore
it should be checked at aonfigure time.

  GEN      ipasetup.py
make[3]: Leaving directory `/workdir/freeipa'
cd .; /usr/bin/python setup.py \
        "--verbose" \
        build \
        --build-base "/workdir/freeipa/ipaclient/build"
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    from ipasetup import ipasetup  # noqa: E402
  File "/workdir/freeipa/ipasetup.py", line 20, in <module>
    from setuptools.command.build_py import build_py as setuptools_build_py
ImportError: No module named setuptools.command.build_py